service: backUpContentful

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "contentfulbackups" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "contentfulbackups"
            - "/*"

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env

functions:
  runBackup:
    handler: handler.runBackup
    events:
      - schedule: rate(1 hour)
    timeout: 300

resources:
  Resources:
    contentfulbackups:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: contentfulbackups
